services:
  neo4j:
    image: neo4j:5
    container_name: neo4j_local
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP for Neo4j Browser
      - "7687:7687" # Bolt for database drivers
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    environment:
      # Set the username and password. IMPORTANT: Change 'your_strong_password'
      - NEO4J_AUTH=neo4j/your_strong_password
      # Install useful plugins like APOC
      - NEO4J_PLUGINS=["apoc"]
      # Set memory limits if needed (optional)
      # - NEO4J_server_memory_pagecache_size=1G
      # - NEO4J_server_memory_heap_initial__size=1G
      # - NEO4J_server_memory_heap_max__size=1G

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
